fragment CategoryGroupFragment on CategoryGroup {
    name
    key
    locale
    publishedAt
    localizations {
        data {
            id
            attributes {
                name
                key
                publishedAt
            }
        }
    }
}
