#import "./address.fragment.gql"
fragment CompanyFragment on Company {
    name
    created_at
    updated_at
    name
    vat
    addresses(
        sort: "created_at:desc"
    ) {
        data {
            id
            attributes {
                ...AddressFragment
            }
        }
    }
}