#import "../../fragments/offering.fragment.gql"
#import "../../fragments/meta.fragment.gql"

query OfferingsQuery(
    $filters: OfferingFiltersInput,
    $pagination: PaginationArg,
    $sort: [String],
    $locale: I18NLocaleCode
    $publicationState: PublicationState,
) {
    offerings(
        filters: $filters,
        pagination: $pagination,
        sort: $sort,
        locale: $locale,
        publicationState: $publicationState
    ) {
        data {
            id
            attributes {
                ...OfferingFragment
            }
        }
        meta {
            ...MetaFragment
        }
    }
}
